// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const dbUrl = process.env.DATABASE_URL || 
  process.env.POSTGRES_URL || 
  process.env.POSTGRES_PRISMA_URL || 
  process.env.livrodaspalavras_PRISMA_DATABASE_URL ||
  process.env.livrodaspalavras_POSTGRES_URL ||
  Object.values(process.env).find(v => typeof v === 'string' && v.startsWith('postgres://') && v.includes('prisma.io')) as string;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: dbUrl,
  },
});
